settings:
  title: 'Uptime Check'
  #url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: about-timvo-au # unique identifier
    name: About Me
    #description: 'About Me' # default=empty
    url: 'https://about.timvo.au' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: AGH-SYD
    name: Adguard Home Sydney
    #description: 'Built for anything connected to the Internet.'
    url: 'https://syd.idns.au'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: AGH-VIE
    name: Adguard Home Vietnam
    url: 'https://vn.idns.au'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: AGH-SIN
    name: Adguard Home Singapore
    url: 'https://sin.idns.au'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: WG-VIE
    name: WireGuard Vietnam
    url: 'https://wg.nhutvo.com/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: WG-MEL
    name: WireGuard Melbourne
    url: 'https://wg.timvo.net/'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
